# values-custom.yaml - Kibana customized for Minikube / EC2
replicas: 1

# موارد الـ Pod
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# إعدادات الاتصال بالـ Elasticsearch
elasticsearchHosts: "http://elasticsearch-master.efk.svc.cluster.local:9200"
elasticsearchSSLVerificationMode: "none"  # تعطيل التحقق من الشهادة TLS

# اسم المستخدم وكلمة المرور للـ Elasticsearch
#extraEnvs:
# - name: ELASTICSEARCH_USERNAME
#   value: "elastic"
# - name: ELASTICSEARCH_PASSWORD
#   value: "FKYpUsCWwbHw0hYb"
# - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
#   value: "none"

# إعدادات الخدمة
service:
  type: NodePort
  nodePort: 30056
  port: 5601

# صحة الـ Pod
#healthCheckPath: "/app/kibana"

# إعدادات الـ Pod/Container
serverHost: "0.0.0.0"
image: "docker.elastic.co/kibana/kibana"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

# Volume / Secrets / Configs إضافية (لو في حاجة)
extraEnvs: []
secretMounts: []
extraVolumes: []
extraVolumeMounts: []

