








global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "mernathawy211@gmail.com"
  smtp_auth_username: "mernathawy211@gmail.com"
  smtp_auth_password: "rzqh dcqp wcpy lvny"
  smtp_require_tls: true

route:
  receiver: "email-alert"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: "email-alert"
  email_configs:
  - to: "mernathawy211@gmail.com"

