replicas: 1

resources:
  requests:
    cpu: "50m"
    memory: "256Mi"
  limits:
    cpu: "150m"
    memory: "512Mi"

# ربط Filebeat بالـ Elasticsearch
elasticsearch:
  hosts: ["http://elasticsearch-master.efk.svc.cluster.local:9200"]

# أي ملفات عايزة تتبعيها
filebeat.inputs:
  - type: log
    paths:
      - /var/log/*.log

# Optional: إذا عايزة تخلي Filebeat يشتغل كـ DaemonSet
# daemonset:
#   enabled: true
output.elasticsearch:
  hosts: ["http://elasticsearch-master:9200"]

setup.kibana:
  host: "http://kibana:5601"

